### ISSUE TITLE
optotag.py cluster definitions

### ISSUE THREAD

**Issue by JoeArthurs** [nbush257/cibrrig#6]
running optotag.py on a file generated an error: AttributeError: 'DataFrame' object has no attribute 'group'. Did you mean: 'drop'

This appears to be linked to the way to script looks for "good" units, which doesn't necessarily match with the way units are classified by spike sorting.

**Comment by nbush257** [comment]
I removed the filtering for good clusters at this level. This should fix the error that you were running into, but now all clusters (even if they are not good) will be assigned as optotagged or not. You will still want to use your QC metrics/manual labelling to only look at good units, but do that filtering at a later step.

**Comment by nbush257** [comment]
New fixes in the case where matlab is not available, falls back on just the KS-test
